// 背景の立体・色糸・スクロール連動、メニュー、動画、反物の色変化。
(()=>{'use strict';const $=id=>document.getElementById(id),canvas=$('canvas'),gl=canvas.getContext('webgl',{alpha:false,antialias:true}),reduced=matchMedia('(prefers-reduced-motion:reduce)');let time=reduced.matches?7:0,life=time,paused=reduced.matches,ready=false,last=0,raf=0,depth=1,original=false,participation=0,scrollShape=0,tx=0,ty=0,mx=0,my=0;
$('fallback').style.visibility='hidden';if(!gl){$('fallback').style.visibility='visible';$('status').textContent='この環境では立体表示が利用できないため原画を表示します。';return}
const off=document.createElement('canvas'),ctx=off.getContext('2d'),mask=document.createElement('canvas'),mc=mask.getContext('2d');off.width=mask.width=1200;off.height=mask.height=848;
const vs=`precision mediump float;attribute vec3 pos;attribute vec2 uv;varying vec2 v;varying float shade;uniform vec2 fit;uniform vec2 angle;uniform float depth;uniform float life;uniform float birth;uniform float impact;uniform vec3 morph;
vec3 form(vec3 p,float mode){
 vec3 c=vec3(-.51,0.,.18),q=p-c;float w=exp(-pow((p.x+.51)/.70,4.));vec3 t=q;
 if(mode>.5&&mode<1.5){t.x=q.x*(1.12+.36*(q.y+.6));t.y=q.y*1.28;t.z=q.z*.65+.16*sin(q.y*4.);}
 else if(mode<2.5&&mode>1.5){float a=q.y*2.7; t.x=q.x*cos(a)-q.z*sin(a);t.z=q.x*sin(a)+q.z*cos(a);t.y=q.y*.96;}
 else if(mode>2.5){t.x=q.x*1.5;t.y=q.y*.68+.22*cos(q.x*5.);t.z=q.z*.38+.38*sin(q.x*4.);}
 return mix(p,t+c,w);
}
void main(){v=uv;vec3 p=mix(form(pos,morph.x),form(pos,morph.y),morph.z);float pulse=sin(life*2.7)+.35*sin(life*5.4);p.z*=depth*(1.+birth*.06*pulse);p.xy*=1.+birth*.009*pulse;float c=cos(angle.x),s=sin(angle.x);p=vec3(p.x*c+p.z*s,p.y,-p.x*s+p.z*c);c=cos(angle.y);s=sin(angle.y);p=vec3(p.x,p.y*c-p.z*s,p.y*s+p.z*c);float k=4./(4.-p.z);shade=.85+.15*clamp(p.z,0.,1.);gl_Position=vec4(p.xy*fit*k,0.,1.);}`;
const fs=`precision mediump float;varying vec2 v;varying float shade;uniform sampler2D art;uniform float back;uniform float opacity;uniform vec4 silkDye;uniform float life;void main(){if(back>.5){vec3 thread=back>1.5?vec3(.61,.43,.18):vec3(.32,.30,.26);float colourBand=.55+.45*smoothstep(-.45,.8,sin(v.x*5.4+v.y*6.283-life*.16));if(back<1.5)thread=mix(thread,silkDye.rgb,silkDye.a*colourBand);gl_FragColor=vec4(thread,opacity);return;}vec3 c=texture2D(art,v).rgb;float a=1.-min(c.r,min(c.g,c.b));if(a<.015)discard;vec3 ink=(c-vec3(1.-a))/max(a,.001);gl_FragColor=vec4(ink*shade,a*opacity);}`;
function shader(type,s){const t=gl.createShader(type);gl.shaderSource(t,s);gl.compileShader(t);if(!gl.getShaderParameter(t,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(t));return t}
let pr;try{pr=gl.createProgram();gl.attachShader(pr,shader(gl.VERTEX_SHADER,vs));gl.attachShader(pr,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(pr);if(!gl.getProgramParameter(pr,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(pr));gl.useProgram(pr)}catch(e){console.error(e);$('fallback').style.visibility='visible';$('status').textContent='立体表示を初期化できないため原画を表示しています。';return}
const U={};['fit','angle','depth','life','birth','art','back','opacity','impact','morph','silkDye'].forEach(n=>U[n]=gl.getUniformLocation(pr,n));const pos=gl.getAttribLocation(pr,'pos'),uv=gl.getAttribLocation(pr,'uv');gl.enableVertexAttribArray(pos);gl.enableVertexAttribArray(uv);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);
function vertex(u,v,back=false){const q=((u-.32)/.215)**2+((v-.52)/.35)**2;const shell=Math.sqrt(Math.max(0,1-Math.min(1,q)));const z=back?-.40*shell:.93*Math.exp(-q*1.2)+.12*Math.exp(-(((u-.66)/.23)**2+((v-.55)/.26)**2));return[(u-.5)*2*1.414,(.5-v)*2,z,u,v]}
function buffer(a){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(a),gl.STATIC_DRAW);return b}function bind(b){gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.vertexAttribPointer(pos,3,gl.FLOAT,false,20,0);gl.vertexAttribPointer(uv,2,gl.FLOAT,false,20,12)}
const nx=160,ny=114,vertices=[],indices=[];for(let y=0;y<=ny;y++)for(let x=0;x<=nx;x++)vertices.push(...vertex(x/nx,y/ny));for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const a=y*(nx+1)+x,b=a+nx+1;indices.push(a,b,a+1,a+1,b,b+1)}const mesh=buffer(vertices),ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(indices),gl.STATIC_DRAW);
const silk=[];for(let i=0;i<=2600;i++){const t=i/2600,a=t*Math.PI*2*23;const v=.51+.29*Math.sin(a*.37)+.018*Math.sin(a*1.71);const width=.19*Math.sqrt(Math.max(0,1-((v-.51)/.33)**2));const u=.32+width*Math.cos(a);const pt=vertex(u,v);pt[2]=.25+.62*Math.sin(a)*Math.sqrt(Math.max(0,1-((v-.51)/.33)**2));silk.push(...pt)}const silkBuffer=buffer(silk);
const backLines=centerlines.filter((p,i)=>i%2===0).map(points=>({b:buffer(points.flatMap(p=>vertex(...p,true))),n:points.length}));const lineLayer=document.createElement("canvas"),lc=lineLayer.getContext("2d");lineLayer.width=1200;lineLayer.height=848;const lineTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,lineTexture);[gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T].forEach(x=>gl.texParameteri(gl.TEXTURE_2D,x,gl.CLAMP_TO_EDGE));gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);[gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T].forEach(x=>gl.texParameteri(gl.TEXTURE_2D,x,gl.CLAMP_TO_EDGE));gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.uniform1i(U.art,0);
const clamp=x=>Math.max(0,Math.min(1,x)),smooth=x=>{x=clamp(x);return x*x*(3-2*x)};const curves=[...centerlines.map((p,i)=>({p,start:i/centerlines.length*1.2,dur:.36})),...nativeLines.map((p,i)=>({p,start:1.15+i/nativeLines.length*.8,dur:.45}))].map(s=>{const p=s.p.map(([x,y])=>[x*1200,y*848]),l=[0];for(let i=1;i<p.length;i++)l.push(l[i-1]+Math.hypot(p[i][0]-p[i-1][0],p[i][1]-p[i-1][1]));return{...s,p,l,total:l.at(-1)}});
// Continuous, equal-length strands: artwork cocoon, dancer, terraced mountain,
// butterfly. Same vertex identities are interpolated throughout the cycle.
const addedThread=document.createElement("span");addedThread.setAttribute("aria-live","polite");addedThread.style.cssText="font-size:12px;color:#807463;padding:10px";
const regionalCount=72,regionalSteps=150,regionalData=new Float32Array(regionalCount*regionalSteps*5),regionalBuffer=gl.createBuffer();
function regionalPoint(mode,j,t){
 const phase=j*2.399963, shell=.84+(j%9)*.018,a=t*Math.PI*2*(2.1+(j%5)*.13)+phase;
 if(mode===0){const p=centerlines[Math.floor(j/regionalCount*centerlines.length)],f=t*(p.length-1),i=Math.min(p.length-2,Math.floor(f)),k=f-i;return vertex(p[i][0]*(1-k)+p[i+1][0]*k,p[i][1]*(1-k)+p[i+1][1]*k).slice(0,3);}
 let x,y,z;
 if(mode===1){
  if(j<10){const b=t*Math.PI; x=.09*Math.sin(b)*Math.cos(a)+.055;y=.60+.11*Math.cos(b);z=.09*Math.sin(b)*Math.sin(a);}
  else if(j<28){const side=j<19?-1:1,gesture=Math.sin(life*.65);x=side*(.07+.42*t)+.055;y=.41+(side<0?.28:-.05)*t+.13*Math.sin(t*Math.PI)+.055*gesture*t;z=.06*Math.sin(a)+.12*t*gesture;x+=.018*Math.cos(a);}
  else {y=.49-1.2*t;const r=t<.30?.10-.045*Math.sin(t/.30*Math.PI):.06+.46*Math.pow((t-.30)/.70,1.3);x=r*shell*Math.cos(a)+.055+.10*Math.sin(t*3.+life*.45)*t;z=r*.48*shell*Math.sin(a);}
 }else if(mode===2){
  const step=Math.floor(t*11)/11,terrace=step+.40*(t-step),r=1.02*terrace*shell;
  x=r*Math.cos(a)-.30*(1-t);y=.48-.90*t+.045*Math.sin(a*3.)*t;z=r*.24*Math.sin(a);
 }else{
  const b=t*Math.PI*4+phase,R=(Math.exp(Math.cos(b))-2*Math.cos(4*b)+Math.pow(Math.sin(b/12),5))*.205*shell;
  x=R*Math.sin(b);y=R*Math.cos(b);z=.025*Math.sin(a);
  const flap=Math.sin(life*1.35)*.42;z+=Math.abs(x)*Math.sin(flap);x*=Math.cos(flap);
 }
 return [x-.51,y,z+.18];
}
function drawRegional(segment,next,blend,alpha){
 if(alpha<=0)return;
 for(let j=0;j<regionalCount;j++)for(let i=0;i<regionalSteps;i++){const t=i/(regionalSteps-1),a=regionalPoint(segment,j,t),b=regionalPoint(next,j,t),k=(j*regionalSteps+i)*5;for(let c=0;c<3;c++)regionalData[k+c]=a[c]*(1-blend)+b[c]*blend;regionalData[k+3]=t;regionalData[k+4]=j/regionalCount;}
 gl.uniform3f(U.morph,0,0,0);gl.uniform1f(U.back,1);gl.uniform1f(U.opacity,.30*alpha);gl.bindBuffer(gl.ARRAY_BUFFER,regionalBuffer);gl.bufferData(gl.ARRAY_BUFFER,regionalData,gl.DYNAMIC_DRAW);bind(regionalBuffer);
 // Small groups of threads carry the supplied textiles' violet, teal,
 // yellow-green and plum. Pigment travels softly along each continuous line.
 const palette=[[.34,.17,.62],[.08,.40,.46],[.57,.59,.15],[.61,.20,.43]],arrival=smooth((time-4.1)/2.9);
 for(let j=0;j<regionalCount;j++){
  const coloured=j%12<4,group=Math.floor(j/12),phase=life*.018+group*.67,idx=Math.floor(phase)%4,k=smooth(phase-Math.floor(phase)),a=palette[idx],b=palette[(idx+1)%4];
  gl.uniform4f(U.silkDye,a[0]+(b[0]-a[0])*k,a[1]+(b[1]-a[1])*k,a[2]+(b[2]-a[2])*k,coloured?.94*arrival:0);
  gl.uniform1f(U.opacity,(coloured?.76:.28)*alpha);
  gl.drawArrays(gl.LINE_STRIP,j*regionalSteps,regionalSteps);
 }
 gl.uniform4f(U.silkDye,0,0,0,0);
 // A visitor can contribute a small, warm thread to the same evolving shape.
 if(participation){gl.uniform1f(U.back,2);gl.uniform1f(U.opacity,.72*alpha);for(let j=0;j<participation;j++)gl.drawArrays(gl.LINE_STRIP,((j*13+7)%regionalCount)*regionalSteps,regionalSteps);}

}

const sections=[...document.querySelectorAll('.chapter')],rail=[...document.querySelectorAll('.rail a')];let targetShape=0;
function updateScroll(){const y=window.scrollY;let index=0;for(let i=0;i<sections.length;i++)if(y>=sections[i].offsetTop-100)index=i;const a=sections[index],b=sections[Math.min(index+1,sections.length-1)];const t=a===b?0:clamp((y+90-a.offsetTop)/(b.offsetTop-a.offsetTop));targetShape=+a.dataset.shape+(+b.dataset.shape-+a.dataset.shape)*smooth(t);document.documentElement.style.setProperty('--scroll',100*y/Math.max(1,document.documentElement.scrollHeight-innerHeight)+'%');rail.forEach((n,i)=>n.setAttribute('aria-current',String(i===index)));document.body.dataset.chapter=a.id;document.getElementById('scene-name').textContent=a.dataset.scene||'COCOON';if(paused||reduced.matches){scrollShape=targetShape;draw();}}
new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('is-visible',e.isIntersecting)),{threshold:.12}).observe(sections[0]);
const reveal=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('is-visible',e.isIntersecting)),{threshold:.12});sections.forEach(s=>reveal.observe(s));
addEventListener('scroll',updateScroll,{passive:true});addEventListener('resize',updateScroll);updateScroll();
const image=new Image();image.onload=()=>{ready=true;draw();canvas.style.opacity='1';schedule()};image.src=artImage;
let textureKey='';function drawTexture(){const key=String(original)+':'+(time>=4?'finished':time.toFixed(3));if(key===textureKey)return;textureKey=key;ctx.globalCompositeOperation='source-over';ctx.clearRect(0,0,1200,848);ctx.fillStyle='#fff';ctx.fillRect(0,0,1200,848);const hit=time-3.1,finish=original?1:clamp(hit/.28);
if(original||finish===1){ctx.drawImage(image,0,0,1200,848)}else if(hit>0){
// A fast, ragged wet front reveals the actual artwork, without replacing its ink texture.
ctx.save();ctx.beginPath();const r=1000*(1-Math.pow(1-finish,3));for(let i=0;i<=160;i++){const a=i/160*Math.PI*2;const jag=1+.10*Math.sin(a*13)+.055*Math.sin(a*29+.7)+.025*Math.sin(a*47);const x=735+Math.cos(a)*r*jag,y=445+Math.sin(a)*r*jag*.72;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.clip();ctx.drawImage(image,0,0,1200,848);ctx.restore();}

if(!original){mc.clearRect(0,0,1200,848);mc.strokeStyle='#fff';mc.lineWidth=4;mc.lineCap='round';mc.lineJoin='round';curves.forEach(s=>{const prog=clamp((time-s.start)/s.dur);if(!prog)return;const target=s.total*prog;mc.beginPath();mc.moveTo(...s.p[0]);for(let j=1;j<s.p.length;j++){if(s.l[j]<=target)mc.lineTo(...s.p[j]);else{const a=s.p[j-1],b=s.p[j],t=(target-s.l[j-1])/(s.l[j]-s.l[j-1]);mc.lineTo(a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t);break}}mc.stroke()});mc.globalCompositeOperation='source-in';mc.drawImage(image,0,0,1200,848);mc.globalCompositeOperation='source-over';ctx.drawImage(mask,0,0);}if(!original&&hit>0&&hit<.75){const spread=1-Math.pow(1-clamp(hit/.21),3),wet=(1-smooth((hit-.10)/.55));ctx.save();ctx.globalAlpha=.22*wet;ctx.globalCompositeOperation='multiply';ctx.drawImage(image,0,0,1200,848);ctx.globalCompositeOperation='source-over';ctx.fillStyle='#393630';ctx.globalAlpha=.72*wet;for(let i=0;i<28;i++){const a=i*2.39996,reach=155+(i%7)*31;const x=770+Math.cos(a)*reach*spread,y=460+Math.sin(a)*reach*.66*spread;const rad=(1.4+(i%4)*.75)*Math.sin(Math.min(1,hit/.035)*Math.PI/2);ctx.beginPath();ctx.ellipse(x,y,rad*(1+spread),rad,a,0,Math.PI*2);ctx.fill()}ctx.restore();}if(!original){
// Separate the traced artwork from the remaining ink. The latter stays on a
// screen-facing plane; only traced lines and the cocoon receive the 3D camera.
lc.clearRect(0,0,1200,848);lc.fillStyle='#fff';lc.fillRect(0,0,1200,848);lc.drawImage(mask,0,0);
gl.bindTexture(gl.TEXTURE_2D,lineTexture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,lineLayer);}
gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,off);}
function draw(){if(!ready)return;drawTexture();const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.round(r.width*d),h=Math.round(r.height*d);if(!w||!h)return;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);gl.clearColor(1,1,1,1);gl.clear(gl.COLOR_BUFFER_BIT);const scale=.88/Math.max(1,1.414/(w/h)),build=smooth(time/1.8),birth=reduced.matches?0:smooth((time-3.5)/1.5);gl.uniform2f(U.fit,scale/(w/h),scale);gl.uniform3f(U.morph,0,0,0);gl.uniform1f(U.depth,0);gl.uniform2f(U.angle,0,0);gl.uniform1f(U.birth,0);gl.uniform1f(U.impact,0);gl.uniform1f(U.life,life);gl.uniform1f(U.back,0);gl.uniform1f(U.opacity,1);gl.bindTexture(gl.TEXTURE_2D,texture);bind(mesh);gl.drawElements(gl.TRIANGLES,indices.length,gl.UNSIGNED_SHORT,0);gl.bindTexture(gl.TEXTURE_2D,lineTexture);const shape=original?0:Math.min(4,Math.max(0,scrollShape)),segment=Math.floor(shape)%4,mixShape=smooth(shape-Math.floor(shape));const regionalAlpha=smooth((time-4.2)/1.3);gl.uniform3f(U.morph,0,0,0);gl.uniform1f(U.depth,original?0:depth*(.25+.75*build));gl.uniform2f(U.angle,original||reduced.matches?0:(Math.sin(life*.16)*.10-.06+Math.sin(scrollShape*1.6)*.22)*build+mx,original||reduced.matches?0:Math.cos(life*.31)*.16*build+my);gl.uniform1f(U.life,life);gl.uniform1f(U.birth,birth);const hit=time-3.1;gl.uniform1f(U.impact,original||reduced.matches||hit<0?0:Math.exp(-hit*12)*Math.sin(Math.min(hit/.10,1)*Math.PI/2));if(!original){gl.uniform1f(U.back,1);gl.uniform1f(U.opacity,.29*smooth(time/.8)*(1-regionalAlpha));backLines.forEach((s,i)=>{const n=Math.floor(s.n*clamp((time-i/backLines.length*.9)/.5));if(n<2)return;bind(s.b);gl.drawArrays(gl.LINE_STRIP,0,n)})}if(!original&&time>0&&time<3.5){const count=Math.min(2601,Math.floor(time/1.55*2601));const fade=1-smooth((time-1.7)/1.8);bind(silkBuffer);gl.uniform1f(U.back,1);gl.uniform1f(U.opacity,.62*fade);gl.drawArrays(gl.LINE_STRIP,0,count);gl.uniform1f(U.opacity,fade);gl.drawArrays(gl.LINE_STRIP,Math.max(0,count-32),Math.min(32,count));}gl.uniform1f(U.back,0);if(!original){gl.uniform1f(U.opacity,1-regionalAlpha);bind(mesh);gl.drawElements(gl.TRIANGLES,indices.length,gl.UNSIGNED_SHORT,0);drawRegional(segment,(segment+1)%4,mixShape,regionalAlpha);}$('progress').value=Math.round(time/7*1000);$('time').textContent=time.toFixed(1)+' / 7s';const phase=time<1.6?0:time<3.1?1:2;$('phase').textContent=['01 / 糸を吐き、繭を紡ぐ','02 / 前後の線が、繭を包む','03 / 平面にインク、立体に鼓動'][phase];if(time>=5.5&&!original){$('phase').textContent='04 / '+['感性を育む繭','身体から生まれる表現','秩父の風景、武甲山','育った感性が羽ばたく'][segment]+(mixShape>0?' → '+['繭','踊り子','武甲山','蝶'][(segment+1)%4]:'');}document.querySelectorAll('[data-seek]').forEach((b,i)=>b.setAttribute('aria-current',i===phase?'step':'false'))}
function state(){document.body.classList.toggle('motion-off',paused);$('pause').textContent=paused?'再生する ▷':'一時停止 Ⅱ';$('pause').setAttribute('aria-pressed',String(paused))}function schedule(){if(!raf&&ready&&!paused&&!document.hidden)raf=requestAnimationFrame(frame)}function frame(now){raf=0;const dt=last?(now-last)/1000:0;last=now;time=Math.min(7,time+dt);life+=dt;scrollShape+=(targetShape-scrollShape)*(1-Math.exp(-dt*6));mx+=(tx-mx)*(1-Math.exp(-dt*4));my+=(ty-my)*(1-Math.exp(-dt*4));draw();schedule()}function clock(){last=0;if(raf)cancelAnimationFrame(raf);raf=0;schedule()}
$('pause').onclick=()=>{paused=!paused;state();clock()};$('replay').onclick=()=>{time=life=0;paused=false;original=false;tx=ty=mx=my=0;$('original').setAttribute('aria-pressed','false');state();draw();clock()};$('original').onclick=()=>{original=!original;$('original').setAttribute('aria-pressed',String(original));draw()};$('depth').oninput=e=>{depth=+e.target.value/100;$('amount').value=e.target.value;draw()};$('progress').oninput=e=>{time=+e.target.value/1000*7;life=time;paused=true;state();draw();clock()};document.querySelectorAll('[data-seek]').forEach(b=>b.onclick=()=>{time=+b.dataset.seek;life=time;paused=true;state();draw();clock()});$('weave').after(addedThread);$('weave').onclick=()=>{original=false;$('original').setAttribute('aria-pressed','false');participation=Math.min(12,participation+1);if(time<5.5){time=7;life=5.5;}addedThread.textContent='あなたの糸が重なりました。';draw();};document.querySelectorAll('[data-motif]').forEach(b=>b.onclick=()=>{time=7;life=5.5+[0,10,17,24][Number(b.dataset.motif)];paused=true;state();draw();clock();});canvas.onpointermove=e=>{if(paused||reduced.matches)return;const r=canvas.getBoundingClientRect();tx=((e.clientX-r.left)/r.width-.5)*.8;ty=((e.clientY-r.top)/r.height-.5)*.35};canvas.onpointerleave=()=>tx=ty=0;new ResizeObserver(draw).observe(canvas);document.addEventListener('visibilitychange',clock);reduced.addEventListener('change',()=>{paused=reduced.matches;if(paused)time=7;state();draw();clock()});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();ready=false;canvas.style.opacity='0';$('fallback').style.visibility='visible';$('status').textContent='立体表示が中断されたため原画を表示します。';clock()});state();
})();

const film=document.querySelector('.process video'),filmButton=document.querySelector('.film-toggle');let filmHeld=false;filmButton.onclick=()=>{if(film.paused){filmHeld=false;film.play().catch(()=>{filmButton.textContent='再生できませんでした。もう一度 ▷'})}else{filmHeld=true;film.pause()}};function filmState(){filmButton.textContent=film.paused?'制作風景を再生 ▷':'一時停止 Ⅱ';filmButton.setAttribute('aria-pressed',String(!film.paused))}film.addEventListener('play',filmState);film.addEventListener('pause',filmState);
/* 画面に入ったら自動再生し、外れたら止める。動きを減らす設定では自動再生しない */
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver'in window){new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){if(!filmHeld&&film.paused)film.play().catch(()=>{})}else if(!film.paused)film.pause()})},{threshold:.35}).observe(film)}
filmState();
const dyeMotion=matchMedia('(prefers-reduced-motion: reduce)');const dyeObserver=new IntersectionObserver(entries=>entries.forEach(e=>{e.target.classList.toggle('is-dyed',e.isIntersecting)}),{threshold:.35});document.querySelectorAll('.dye-image').forEach(e=>dyeObserver.observe(e));
const videoObserver=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)e.target.pause()}),{threshold:.05});document.querySelectorAll('video').forEach(v=>videoObserver.observe(v));document.addEventListener('visibilitychange',()=>{if(document.hidden)document.querySelectorAll('video').forEach(v=>v.pause())});
const mt=document.getElementById('menu-toggle'),mm=document.getElementById('mobile-menu');function closeMenu(){mm.hidden=true;mt.setAttribute('aria-expanded','false')}mt.onclick=()=>{mm.hidden=!mm.hidden;mt.setAttribute('aria-expanded',String(!mm.hidden))};mm.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();mt.focus()}});
